#!/usr/bin/env ruby

# /via https://github.com/ryanb/dotfiles/tree/master/bash/completion_scripts

class ProjectCompletion
  def initialize(command)
    @command = command
  end

  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def projects
    `ls $PROJECTS`.split
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
