#!/usr/bin/env bash

EXTENSIONS=(
	"pejdijmoenmkgeppbflobdenhhabjlaj" # iCloud Passwords
	"gighmmpiobklfepjocnamgkkbiglidom" # Adblock
	# "omdakjcmkglenbhjadbccaookpfjihpa" # TunnelBear VPN
)

CHROME_EXTENSION_PATH="$HOME/Library/Application Support/Google/Chrome/External Extensions/"
mkdir -p "$CHROME_EXTENSION_PATH"

for extension in "${EXTENSIONS[@]}" ; do
	echo "{ \"external_update_url\": \"https://clients2.google.com/service/update2/crx\" }" > "$CHROME_EXTENSION_PATH/$extension.json"
done
