#!/usr/bin/env zsh

# remove all symlinks to these dotfiles

FILES=($(cat ./files-to-symlink-in-homedir))

for file in $FILES; do
    # is file a symlink?
    if [[ -L $HOME/$file ]]; then
        rm $HOME/$file
    fi
done
